export const PayHistorySearchableFields = [
    'age',
    'name',
    'email',
    'phone',
    'address',
    'role',
    'point',
    'payment',
    'photo',
    'cover',
    'about',
    'facebook',
    'insta',
    'blood',
  ]
  
  export const PayHistoryFilterableFields = [
    'searchTerm',
    'age',
    'name',
    'email',
    'phone',
    'address',
    'role',
    'point',
    'payment',
    'photo',
    'cover',
    'about',
    'facebook',
    'insta',
    'blood',
  ]